import type { MenuThemeId, PublicLocale, ThemeCopy, ThemeDefinition } from './types';

export const THEME_REGISTRY: Record<MenuThemeId, ThemeDefinition> = {
  elegant: {
    id: 'elegant',
    name: 'Elegant',
    tagline: 'Premium Restoran & Fine Dining',
    description: 'Zarif serif tipografi, derin altın ışıltısı ve lüks kart yapısıyla fine dining ve butik işletmeler için idealdir.',
    category: 'luxury',
    badge: 'Fine Dining · Otel',
    accentColor: '#d4af37',
    previewThumbnail: 'linear-gradient(135deg, #0c0e12 0%, #1f1b14 100%)',
    isFree: true,
    planRequired: 'FREE',
    features: ['Serif Başlıklar', 'Altın & Bronz Vurgular', 'Lüks Giriş Ekranı', 'Genişletilmiş Detay Kartı'],
  },
  modern: {
    id: 'modern',
    name: 'Modern',
    tagline: 'Yeni Nesil Kafe & Coffee Shop',
    description: 'Temiz, akıcı cam efektleri (glassmorphism), yuvarlak modern hatlar ve canlı dinamik sekmeler sunar.',
    category: 'modern',
    badge: '3rd Wave Kafe · Bistro',
    accentColor: '#06b6d4',
    previewThumbnail: 'linear-gradient(135deg, #0f172a 0%, #0e2e38 100%)',
    isFree: true,
    planRequired: 'FREE',
    features: ['Glassmorphism Header', 'Floating Kategori Hapları', 'Teal & Zümrüt Aksanlar', 'Modern Dokunma Hissi'],
  },
  classic: {
    id: 'classic',
    name: 'Classic',
    tagline: 'Geleneksel Restoran & Ocakbaşı',
    description: 'Sıcak odunsu ve kehribar tonları, geleneksel menü kemerleri ve samimi lezzet sunumuyla kebapçı ve lokantalar için özeldir.',
    category: 'traditional',
    badge: 'Restoran · Kebapçı · Lokanta',
    accentColor: '#e06d3b',
    previewThumbnail: 'linear-gradient(135deg, #1a1311 0%, #2e1c15 100%)',
    isFree: true,
    planRequired: 'FREE',
    features: ['Sıcak Kehribar & Parşömen', 'Geleneksel Amblem Rozetleri', 'Nostaljik Fiyat Şeritleri', 'Okunaklı Menü Düzeni'],
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    tagline: 'Sade, Ultra Hızlı & Monokrom',
    description: 'Saf monokrom siyah-beyaz zıtlığı, keskin tipografik grid ve içeriğe odaklanan sıfır dikkat dağıtıcı tasarım.',
    category: 'clean',
    badge: 'Studio · İskandinav · Galeri',
    accentColor: '#ffffff',
    previewThumbnail: 'linear-gradient(135deg, #050505 0%, #171717 100%)',
    isFree: true,
    planRequired: 'FREE',
    features: ['Monokrom Yüksek Kontrast', 'Ultra Hızlı Yüklenme', 'Geometrik Sans Tipografi', 'Sade Liste Görünümü'],
  },
  bold: {
    id: 'bold',
    name: 'Bold',
    tagline: 'Genç Kafe, Burger & Sokak Lezzetleri',
    description: 'Güçlü ve iri tipografi, elektrik sarısı ve neon vurgular, doyurucu büyük ürün kartları ve dinamik eğlenceli enerji.',
    category: 'energetic',
    badge: 'Burger House · Street Food · Pub',
    accentColor: '#facc15',
    previewThumbnail: 'linear-gradient(135deg, #130f26 0%, #2c1a06 100%)',
    isFree: true,
    planRequired: 'FREE',
    features: ['Punchy Heavy Tipografi', 'Neon Sarı & Turuncu Vurgular', 'Sticker Tarzı Rozetler', 'Büyük Doyurucu Görseller'],
  },
};

export const THEME_LIST: ThemeDefinition[] = Object.values(THEME_REGISTRY);

export const THEME_COPIES: Record<PublicLocale, ThemeCopy> = {
  tr: {
    menuKicker: 'DİJİTAL MENÜ',
    menuTitle: 'Menü',
    searchPlaceholder: 'Menüde ara (kahve, burger, tatlı)...',
    noSearchResults: 'Aramanızla eşleşen lezzet bulunamadı.',
    noProducts: 'Bu menüde henüz ürün listelenmemektedir.',
    menuUpdatingTitle: 'Menümüz Güncelleniyor',
    menuUpdatingDesc: 'İşletmemizin dijital menüsü şu anda güncellenmektedir. Lütfen kısa bir süre sonra tekrar deneyiniz.',
    featured: 'ÖNE ÇIKAN',
    close: 'Kapat',
    details: 'ÜRÜN DETAYI',
    noDesc: 'Bu ürün için henüz detaylı açıklama girilmemiştir.',
    createdWith: 'Bu dijital menü Pratika QR ile oluşturuldu.',
    createYourMenu: 'Kendi işletmeniz için profesyonel bir QR menü oluşturun.',
    createCta: 'QR Menümü Oluştur',
    allergensLabel: 'İçerik ve alerjen bilgisi için lütfen servis personelimize danışınız.',
    viewMenuBtn: 'Menüyü Gör',
    welcomeEyebrow: 'HOŞ GELDİNİZ',
    welcomeSub: 'Keyifli lezzet deneyimi için menümüzü inceleyin.',
    infoTitle: 'İşletme Bilgileri',
    callBtn: 'Ara',
    instagramBtn: 'Instagram',
    hoursLabel: 'Çalışma Saatleri',
    addressLabel: 'Adres',
    exploreCategories: 'Kategoriler',
    backToWelcome: 'Karşılama Ekranı',
  },
  en: {
    menuKicker: 'DIGITAL MENU',
    menuTitle: 'Menu',
    searchPlaceholder: 'Search menu (coffee, burger, dessert)...',
    noSearchResults: 'No items found matching your search.',
    noProducts: 'No products listed in this menu yet.',
    menuUpdatingTitle: 'Menu Updating',
    menuUpdatingDesc: 'Our digital menu is currently being updated. Please check back shortly.',
    featured: 'FEATURED',
    close: 'Close',
    details: 'ITEM DETAILS',
    noDesc: 'No detailed description available for this item.',
    createdWith: 'This digital menu was created with Pratika QR.',
    createYourMenu: 'Create a professional QR menu for your business.',
    createCta: 'Create My QR Menu',
    allergensLabel: 'Please ask our service staff for ingredients and allergen information.',
    viewMenuBtn: 'Explore Menu',
    welcomeEyebrow: 'WELCOME',
    welcomeSub: 'Explore our delightful culinary offerings.',
    infoTitle: 'Business Information',
    callBtn: 'Call',
    instagramBtn: 'Instagram',
    hoursLabel: 'Opening Hours',
    addressLabel: 'Address',
    exploreCategories: 'Categories',
    backToWelcome: 'Welcome Screen',
  },
  de: {
    menuKicker: 'DIGITALE SPEISEKARTE',
    menuTitle: 'Speisekarte',
    searchPlaceholder: 'Im Menü suchen (Kaffee, Burger, Dessert)...',
    noSearchResults: 'Keine passenden Spezialitäten gefunden.',
    noProducts: 'In dieser Speisekarte sind noch keine Produkte gelistet.',
    menuUpdatingTitle: 'Menü wird aktualisiert',
    menuUpdatingDesc: 'Unsere Speisekarte wird derzeit überarbeitet. Bitte versuchen Sie es in Kürze erneut.',
    featured: 'EMPFEHLUNG',
    close: 'Schließen',
    details: 'PRODUKTDETAILS',
    noDesc: 'Keine detaillierte Beschreibung für dieses Produkt verfügbar.',
    createdWith: 'Diese Speisekarte wurde mit Pratika QR erstellt.',
    createYourMenu: 'Erstellen Sie ein professionelles QR-Menü für Ihr Unternehmen.',
    createCta: 'Mein QR-Menü erstellen',
    allergensLabel: 'Für Inhaltsstoffe und Allergene fragen Sie bitte unser Servicepersonal.',
    viewMenuBtn: 'Speisekarte ansehen',
    welcomeEyebrow: 'HERZLICH WILLKOMMEN',
    welcomeSub: 'Entdecken Sie unsere kulinarische Vielfalt.',
    infoTitle: 'Betriebsinformationen',
    callBtn: 'Anrufen',
    instagramBtn: 'Instagram',
    hoursLabel: 'Öffnungszeiten',
    addressLabel: 'Adresse',
    exploreCategories: 'Kategorien',
    backToWelcome: 'Startbildschirm',
  },
  ru: {
    menuKicker: 'ЦИФРОВОЕ МЕНЮ',
    menuTitle: 'Меню',
    searchPlaceholder: 'Поиск по меню (кофе, бургер, десерт)...',
    noSearchResults: 'Блюда не найдены.',
    noProducts: 'В этом меню пока нет товаров.',
    menuUpdatingTitle: 'Меню обновляется',
    menuUpdatingDesc: 'Наше меню в настоящее время обновляется. Пожалуйста, зайдите позже.',
    featured: 'ХИТ',
    close: 'Закрыть',
    details: 'О БЛЮДЕ',
    noDesc: 'Подробное описание отсутствует.',
    createdWith: 'Это цифровое меню создано с помощью Pratika QR.',
    createYourMenu: 'Создайте профессиональное QR-меню для своего заведения.',
    createCta: 'Создать моё QR-меню',
    allergensLabel: 'Информацию о составе и аллергенах можно уточнить у персонала.',
    viewMenuBtn: 'Смотреть меню',
    welcomeEyebrow: 'ДОБРО ПОЖАЛОВАТЬ',
    welcomeSub: 'Ознакомьтесь с нашим вкусным меню.',
    infoTitle: 'Информация',
    callBtn: 'Позвонить',
    instagramBtn: 'Instagram',
    hoursLabel: 'Часы работы',
    addressLabel: 'Адрес',
    exploreCategories: 'Категории',
    backToWelcome: 'Экран приветствия',
  },
};

/**
 * Returns whether a given theme is accessible for a business (pricing / entitlement hook)
 */
export function isThemeAccessible(themeId: MenuThemeId, userPlan?: string): boolean {
  const theme = THEME_REGISTRY[themeId];
  if (!theme) return false;
  if (theme.isFree) return true;
  // Future entitlement / billing plan checks can hook here seamlessly:
  if (userPlan === 'PRO' || userPlan === 'ENTERPRISE') return true;
  return true;
}

export function sanitizeThemeId(themeId?: string | null): MenuThemeId {
  if (themeId && themeId in THEME_REGISTRY) {
    return themeId as MenuThemeId;
  }
  return 'elegant';
}
